import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import {
  BLINK_REACTION_ID,
  DEFAULT_PIVOT,
  DEFAULT_REACTION_POSE,
  BuddyMotion,
  MOTION_LIMITS,
  PAGE_PET_TUNING,
  REACTION_POSES,
  cssMatrix,
  ease,
  identityTransform,
  isIdentityTransform,
  reactionPose,
  type MotionConfig,
  type MotionTransform
} from './buddy-motion'

type FixtureOp =
  | { at: number; op: 'react'; reaction: string }
  | { at: number; op: 'nudge'; y: number; angle: number }
  | { at: number; op: 'gazeTurn'; deltaX: number }
  | { at: number; op: 'talkBob' }
  | { at: number; op: 'idle'; idle: boolean }

interface MotionFixture {
  version: number
  stepSeconds: number
  samples: number
  tolerance: number
  tuning: MotionConfig['tuning']
  easingPoints: number
  easings: Record<string, number[]>
  cases: {
    name: string
    intensity: number
    size: number
    breathing: boolean
    script: FixtureOp[]
    transform: number[][]
  }[]
}

// Generated by the Rust model: `cargo test -p videorc-backend
// buddy_motion::tests::write_shared_fixture -- --ignored`. This test proves
// the TypeScript twin produces the same samples (plan 168 S-C1, D6).
const fixture = JSON.parse(
  readFileSync(new URL('../../../../protocol-fixtures/buddy-motion.json', import.meta.url), 'utf8')
) as MotionFixture

const POSE_IDS = Object.keys(REACTION_POSES)

function apply(model: BuddyMotion, op: FixtureOp): void {
  switch (op.op) {
    case 'react':
      model.react(op.reaction, op.at)
      break
    case 'nudge':
      model.nudge(op.y, op.angle)
      break
    case 'gazeTurn':
      model.gazeTurn(op.deltaX)
      break
    case 'talkBob':
      model.talkBob()
      break
    case 'idle':
      model.setIdle(op.idle)
      break
  }
}

function row(t: MotionTransform): number[] {
  return [t.translateX, t.translateY, t.rotationDeg, t.skewXDeg, t.scaleX, t.scaleY]
}

function replay(
  config: Partial<MotionConfig>,
  script: FixtureOp[],
  step: number,
  samples: number
): number[][] {
  const model = new BuddyMotion(config)
  let next = 0
  const out: number[][] = []
  for (let i = 0; i < samples; i += 1) {
    const now = i * step
    while (next < script.length && script[next].at <= now) {
      apply(model, script[next])
      next += 1
    }
    out.push(row(model.advance(now)))
  }
  return out
}

function expectRowsClose(name: string, got: number[][], want: number[][], tolerance: number): void {
  expect(got.length, name).toBe(want.length)
  for (let i = 0; i < got.length; i += 1) {
    for (let k = 0; k < 6; k += 1) {
      const delta = Math.abs(got[i][k] - want[i][k])
      if (!(delta <= tolerance)) {
        throw new Error(
          `${name} sample ${i} channel ${k}: ts ${got[i][k]} fixture ${want[i][k]} (delta ${delta})`
        )
      }
    }
  }
}

describe('shared buddy motion fixture', () => {
  it('covers every pose id, the default pose, a nudge, a gaze turn, talk and breathing', () => {
    const names = new Set(fixture.cases.map((c) => c.name.split('@')[0]))
    for (const id of POSE_IDS) expect(names.has(`reaction:${id}`), id).toBe(true)
    for (const name of ['reaction:unknown-pose', 'nudge', 'gaze-turn', 'talk', 'breathing']) {
      expect(names.has(name), name).toBe(true)
    }
    const variants = new Set(fixture.cases.map((c) => `${c.intensity}x${c.size}`))
    expect([...variants].sort()).toEqual(['0.45x180', '0.45x360', '1x180', '1x360'])
    expect(fixture.samples).toBe(121)
    expect(fixture.stepSeconds).toBeCloseTo(1 / 60, 12)
    expect(fixture.tolerance).toBe(1e-4)
    expect(fixture.tuning).toEqual(PAGE_PET_TUNING)
  })

  it('matches the Rust model within the tolerance on every case', () => {
    for (const c of fixture.cases) {
      const got = replay(
        { intensity: c.intensity, size: c.size, breathing: c.breathing },
        c.script,
        fixture.stepSeconds,
        fixture.samples
      )
      expectRowsClose(c.name, got, c.transform, fixture.tolerance)
    }
  })

  it('agrees with Rust on the easing functions at 101 points', () => {
    const points = fixture.easingPoints
    expect(points).toBe(101)
    const table: Record<string, (p: number) => number> = {
      power2Out: ease.power2Out,
      power3Out: ease.power3Out,
      sineInOut: ease.sineInOut,
      'elasticOut(1,0.45)': (p) => ease.elasticOut(p, 1, 0.45),
      'elasticOut(1,0.3)': (p) => ease.elasticOut(p, 1, 0.3),
      'elasticOut(1,0.55)': (p) => ease.elasticOut(p, 1, 0.55)
    }
    for (const [name, fn] of Object.entries(table)) {
      const want = fixture.easings[name]
      expect(want, name).toHaveLength(points)
      for (let i = 0; i < points; i += 1) {
        const p = i / (points - 1)
        expect(Math.abs(fn(p) - want[i]), `${name} at ${p}`).toBeLessThanOrEqual(fixture.tolerance)
      }
    }
  })
})

describe('BuddyMotion', () => {
  it('is the identity at intensity 0 for every reaction', () => {
    for (const id of [...POSE_IDS, 'unknown-pose', BLINK_REACTION_ID]) {
      const model = new BuddyMotion({ intensity: 0 })
      expect(model.react(id, 0), id).toBe(0)
      model.gazeTurn(1)
      model.talkBob()
      for (let i = 0; i <= 120; i += 1) {
        expect(isIdentityTransform(model.advance(i / 60)), `${id} sample ${i}`).toBe(true)
      }
    }
  })

  it('removes the transform at once when the intensity drops to 0 mid-flight', () => {
    const model = new BuddyMotion()
    model.react('surprised', 0)
    expect(isIdentityTransform(model.advance(0.2))).toBe(false)
    model.setConfig({ intensity: 0 })
    expect(isIdentityTransform(model.advance(0.21))).toBe(true)
  })

  it('keeps every page-pet pose plus the hop, and falls back to the default for unknown ids', () => {
    // page-pet's 15 poses plus Videorc's motion-only hop.
    expect(POSE_IDS).toHaveLength(16)
    expect(reactionPose('hop')).toEqual([-22, 0, -0.12])
    expect(reactionPose('surprised')).toEqual([-17, -3, -0.1])
    expect(reactionPose('laugh')).toEqual([-9, 3, 0.065])
    expect(reactionPose('excited')).toEqual([-20, 4, -0.11])
    expect(reactionPose('think')).toBe(DEFAULT_REACTION_POSE)
    expect(reactionPose('constructor')).toBe(DEFAULT_REACTION_POSE)
  })

  it('reports page-pet envelope lengths', () => {
    const model = new BuddyMotion()
    expect(model.react('surprised', 1)).toBeCloseTo(0.87, 12)
    expect(model.reactionEndsAt()).toBeCloseTo(1.87, 12)
    expect(model.react('laugh', 1)).toBeCloseTo(1.09, 12)
    expect(model.react(BLINK_REACTION_ID, 1)).toBe(0)
    const fast = new BuddyMotion({ tuning: { ...PAGE_PET_TUNING, speed: 1.5, bounce: 0 } })
    expect(fast.react('wink', 0)).toBeCloseTo(0.75 / 1.5, 12)
  })

  it('crouches, reaches the pose, overshoots on the elastic return and rests', () => {
    const model = new BuddyMotion({ intensity: 1, breathing: false })
    model.react('surprised', 0)
    const amount = PAGE_PET_TUNING.reaction
    const crouch = model.advance(0.11)
    expect(crouch.translateY).toBeCloseTo(3 * amount, 9)
    expect(crouch.scaleX).toBeCloseTo(1 + 0.045 * amount, 9)
    const pose = model.advance(0.3)
    expect(pose.translateY).toBeCloseTo(-17 * amount, 9)
    expect(pose.rotationDeg).toBeCloseTo(-3 * amount, 9)
    expect(pose.scaleX * pose.scaleY).toBeCloseTo(1, 12)
    let crossed = false
    for (let t = 0.3; t < 0.87; t += 1 / 240) {
      if (model.advance(t).translateY > 0.1) crossed = true
    }
    expect(crossed).toBe(true)
    expect(isIdentityTransform(model.advance(0.9))).toBe(true)
    expect(model.reactionEndsAt()).toBeNull()
  })

  it('holds the clamps, scales translation by size and preserves area', () => {
    const model = new BuddyMotion({ intensity: 1, size: 360, breathing: false })
    for (let i = 0; i < 40; i += 1) model.nudge(-500, 500)
    model.react('excited', 0)
    for (let t = 1 / 60; t < 2; t += 1 / 60) {
      const out = model.advance(t)
      const c = model.channels()
      expect(Math.abs(c.x)).toBeLessThanOrEqual(MOTION_LIMITS.xPx)
      expect(Math.abs(c.y)).toBeLessThanOrEqual(MOTION_LIMITS.yPx)
      expect(Math.abs(c.angle)).toBeLessThanOrEqual(MOTION_LIMITS.rotationDeg)
      expect(Math.abs(c.skew)).toBeLessThanOrEqual(MOTION_LIMITS.skewDeg)
      expect(Math.abs(c.squash)).toBeLessThanOrEqual(MOTION_LIMITS.squash)
      expect(out.translateY).toBeCloseTo(c.y * 2, 9)
      expect(out.scaleX * out.scaleY).toBeCloseTo(1, 12)
    }
  })

  it('breathes only while idle, with the persona setting on, and never steps', () => {
    const model = new BuddyMotion()
    let seen = 0
    let previous = model.advance(0).scaleX
    for (let i = 1; i <= 240; i += 1) {
      const out = model.advance(i / 60)
      seen = Math.max(seen, Math.abs(out.scaleX - 1))
      expect(Math.abs(out.scaleX - previous)).toBeLessThan(0.001)
      previous = out.scaleX
      expect(out.translateX).toBe(0)
      expect(out.rotationDeg).toBe(0)
    }
    expect(seen).toBeGreaterThan(0.012 * 0.45 * 0.9)
    expect(seen).toBeLessThanOrEqual(0.012 * 0.45 + 1e-12)
    model.setIdle(false)
    for (let i = 1; i <= 240; i += 1) model.advance(4 + i / 60)
    expect(isIdentityTransform(model.transform())).toBe(true)
    const still = new BuddyMotion({ breathing: false })
    for (let i = 0; i <= 180; i += 1) expect(isIdentityTransform(still.advance(i / 60))).toBe(true)
  })

  it('stops to rest at once', () => {
    const model = new BuddyMotion()
    model.react('dance', 0)
    model.nudge(-50, 20)
    model.advance(0.2)
    expect(isIdentityTransform(model.transform())).toBe(false)
    model.stop()
    expect(model.isResting()).toBe(true)
    expect(isIdentityTransform(model.transform())).toBe(true)
  })

  it('composes rotate, skewX and scale into a CSS matrix', () => {
    expect(cssMatrix(identityTransform(DEFAULT_PIVOT))).toEqual([1, 0, 0, 1, 0, 0])
    const turned = cssMatrix({
      ...identityTransform(DEFAULT_PIVOT),
      rotationDeg: 90,
      translateX: 3,
      translateY: -4
    })
    expect(turned[0]).toBeCloseTo(0, 12)
    expect(turned[1]).toBeCloseTo(1, 12)
    expect(turned[2]).toBeCloseTo(-1, 12)
    expect(turned[3]).toBeCloseTo(0, 12)
    expect(turned.slice(4)).toEqual([3, -4])
    const scaled = cssMatrix({
      ...identityTransform(DEFAULT_PIVOT),
      scaleX: 1.1,
      scaleY: 1 / 1.1,
      skewXDeg: 45
    })
    expect(scaled[0]).toBeCloseTo(1.1, 12)
    expect(scaled[2]).toBeCloseTo(1 / 1.1, 12)
    expect(scaled[3]).toBeCloseTo(1 / 1.1, 12)
  })
})
