import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildIconModule,
  extractBody,
  extractViewBox,
  findInlineStyleColours,
  normalizeColours,
  renderComponent,
  toComponentName
} from './icon-build.mjs'

const OUTLINE_EXPORT = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <!-- Generated by a vendor tool -->
  <title>alert</title>
  <g id="alert-group" class="nc-icon-wrapper" stroke="#212121" fill="none">
    <circle cx="12" cy="12" r="9" stroke-width="1.5"/>
    <path d="M12 8v5" stroke-width="1.5"/>
  </g>
</svg>`

test('viewBox is required and preserved', () => {
  assert.equal(extractViewBox(OUTLINE_EXPORT), '0 0 24 24')
  assert.throws(() => extractViewBox('<svg width="24"></svg>'), /viewBox/)
})

test('body drops vendor metadata, ids and classes', () => {
  const body = extractBody(OUTLINE_EXPORT)
  assert.doesNotMatch(body, /<title/)
  assert.doesNotMatch(body, /Generated by/)
  // ids collide the moment two icons are inlined on one page; classes leak
  // the vendor's own stylesheet expectations.
  assert.doesNotMatch(body, /\bid=/)
  assert.doesNotMatch(body, /\bclass=/)
  assert.match(body, /<circle/)
  assert.match(body, /<path/)
})

test('hard-coded colours become currentColor but structural none survives', () => {
  const body = normalizeColours(extractBody(OUTLINE_EXPORT))
  assert.match(body, /stroke="currentColor"/)
  assert.doesNotMatch(body, /#212121/)
  // fill="none" is geometry, not colour: an outline icon must keep it or it
  // renders as a filled blob.
  assert.match(body, /fill="none"/)
})

test('inline style colours are reported rather than silently shipped', () => {
  const styled = '<path style="fill:#ff0000" d="M0 0"/>'
  assert.equal(findInlineStyleColours(styled).length, 1)
  assert.equal(findInlineStyleColours('<path style="opacity:.5"/>').length, 0)
})

test('component names come from file names', () => {
  assert.equal(toComponentName('alert-circle.svg'), 'AlertCircle')
  assert.equal(toComponentName('video_camera.svg'), 'VideoCamera')
  assert.equal(toComponentName('4k-badge.svg'), 'Icon4kBadge')
  assert.throws(() => toComponentName('---.svg'), /component name/)
})

test('generated components size from one prop and swallow weight', () => {
  const source = renderComponent({ name: 'AlertCircle', viewBox: '0 0 24 24', body: '<circle/>' })
  // Call sites still pass weight from the previous icon set; a single-weight
  // export has nothing to switch on, so it must be accepted and ignored
  // rather than forwarded into the DOM as an unknown attribute.
  assert.match(source, /weight: _weight/)
  assert.match(source, /width=\{size\}/)
  assert.match(source, /height=\{size\}/)
  assert.match(source, /viewBox="0 0 24 24"/)
})

test('a full module builds and refuses an export that still carries colours', () => {
  const module = buildIconModule([{ name: 'alert-circle.svg', contents: OUTLINE_EXPORT }])
  assert.match(module, /GENERATED by scripts\/build-icons\.mjs/)
  assert.match(module, /export function AlertCircle/)
  assert.throws(
    () =>
      buildIconModule([
        { name: 'bad.svg', contents: '<svg viewBox="0 0 24 24"><path style="fill:#f00"/></svg>' }
      ]),
    /re-export without styles/
  )
})
