// Turns an exported icon SVG into a Videorc icon component.
//
// Dependency-free on purpose: this repo is public and the icon build must not
// pull an SVG toolchain into everyone's install just so the maintainer can
// refresh a licensed icon set.
//
// The transform enforces the three rules the design language depends on:
//   1. Colour comes from `currentColor`, never from the file — the chrome is
//      monochrome and icons tint with their text.
//   2. No fixed width/height — size is a class or a prop, so one export
//      serves both the 16px inline and 24px nav sizes.
//   3. No ids, classes, titles or metadata — ids collide once two icons are
//      inlined on the same page, and stray classes leak the vendor's styling.

/** Attributes that hard-code a colour and must defer to `currentColor`. */
const COLOUR_ATTRIBUTES = ['fill', 'stroke']

export function extractViewBox(svg) {
  const match = svg.match(/<svg\b[^>]*\bviewBox\s*=\s*["']([^"']+)["']/i)
  if (!match) {
    throw new Error('icon SVG has no viewBox; export with a viewBox so it can scale')
  }
  return match[1].trim()
}

/**
 * Everything between <svg> and </svg>, cleaned. Comments, XML prologues,
 * <title>/<desc>/<defs id=…> metadata and editor cruft are dropped: an icon
 * is geometry, and anything else is either noise or an id waiting to collide.
 */
export function extractBody(svg) {
  const open = svg.search(/<svg\b/i)
  const bodyStart = svg.indexOf('>', open) + 1
  const bodyEnd = svg.lastIndexOf('</svg')
  if (open === -1 || bodyEnd === -1) {
    throw new Error('icon SVG has no <svg> element')
  }
  return svg
    .slice(bodyStart, bodyEnd)
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<title\b[\s\S]*?<\/title>/gi, '')
    .replace(/<desc\b[\s\S]*?<\/desc>/gi, '')
    .replace(/<metadata\b[\s\S]*?<\/metadata>/gi, '')
    .replace(/\s(?:id|class)\s*=\s*["'][^"']*["']/gi, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Rewrites hard-coded colours to `currentColor`. `none` is preserved — it is
 * structural (an outline icon fills `none` and strokes the path), not a
 * colour choice.
 */
export function normalizeColours(body) {
  let next = body
  for (const attribute of COLOUR_ATTRIBUTES) {
    next = next.replace(
      new RegExp(`\\s${attribute}\\s*=\\s*["']([^"']*)["']`, 'gi'),
      (whole, value) =>
        value.trim().toLowerCase() === 'none' ? whole : ` ${attribute}="currentColor"`
    )
  }
  return next
}

/** Reports colours the export left behind in a style attribute. */
export function findInlineStyleColours(body) {
  return [...body.matchAll(/\sstyle\s*=\s*["']([^"']*)["']/gi)]
    .map((match) => match[1])
    .filter((style) => /(fill|stroke)\s*:/i.test(style))
}

export function toComponentName(fileName) {
  const base = fileName.replace(/\.svg$/i, '')
  const pascal = base
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
  if (!pascal) {
    throw new Error(`icon file name "${fileName}" produces no component name`)
  }
  return /^[0-9]/.test(pascal) ? `Icon${pascal}` : pascal
}

/**
 * One generated component. `weight` is accepted and ignored: the app's call
 * sites carry it from the previous icon set, and a single-weight export has
 * nothing to switch on. Dropping the prop instead would mean editing 100+
 * call sites for no visual gain.
 */
export function renderComponent({ name, viewBox, body }) {
  return `export function ${name}({ size = '1em', weight: _weight, ...props }: AppIconProps): ReactElement {
  return (
    <svg
      viewBox="${viewBox}"
      width={size}
      height={size}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      ${body}
    </svg>
  )
}`
}

export function buildIconModule(files) {
  const components = files.map((file) => {
    const viewBox = extractViewBox(file.contents)
    const body = normalizeColours(extractBody(file.contents))
    const leftovers = findInlineStyleColours(body)
    if (leftovers.length > 0) {
      throw new Error(
        `${file.name}: inline style colours (${leftovers.join('; ')}) survive the transform — re-export without styles`
      )
    }
    return renderComponent({ name: toComponentName(file.name), viewBox, body })
  })
  return `${GENERATED_HEADER}\n${components.join('\n\n')}\n`
}

export const GENERATED_HEADER = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
//
// Source: the licensed icon export under vendor/icons/. Re-run \`pnpm icons:build\`
// after changing that folder. See docs/icon-set.md for the licence terms that
// govern how many icons may ship and where the export may live.
import type { ReactElement } from 'react'

import type { AppIconProps } from '@/components/icons'
`
